version: "3.9"
services:
  db:
    hostname: db
    image: postgres:15.2-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

  web-api:
    build: .
    command: poetry run uvicorn main:app --workers 1 --host 0.0.0.0 --port 8000
    restart: always
    working_dir: /app/src
    ports:
      - "80:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    networks:
    - backend-network
volumes:
  my-db:
  db:

networks:
  backend-network:
    driver: bridge